[package]
name = "btctipserver-liquid"
version = "0.1.1-dev"

[dependencies]
edk = { git = "https://github.com/lvaccaro/edk.git" }
dirs-next = "2.0.0"
structopt = "0.3"
hex = "0.4"

[features]
electrum = ["edk/electrum"]
